version: '3'
services:
  postgres:
    container_name: my_db_container
    restart: always
    image: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    ports:
      - 8839:5432
